org.gradle.jvmargs=-Xms1g -Xmx3g -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options=-Xms512m,-Xmx2g
org.gradle.daemon=true
android.useAndroidX=true
android.enableJetifier=true

## Evitar problemas de snapshotting/FS watch en rutas OneDrive/Windows
org.gradle.vfs.watch=false
org.gradle.unsafe.watch-fs=false
org.gradle.configuration-cache=false

